# import matplotlib
# matplotlib.use('TkAgg')
# from matplotlib import pyplot as plt
from statistics import mean
import matplotlib.pyplot as plt


def visualize_random(list_of_scores, N):
    """
    Visualizes a list of scores generated by
    the random algorithm into a box plot.
    """

    average = mean(list_of_scores)
    minimum = min(list_of_scores)


    plt.boxplot(list_of_scores)
    plt.title(f"Malus points of all valid schedules\nafter {N} iterations of the random algorithm")
    plt.xticks([])
    plt.xlabel(f"Average: {round(average)}\nMinimum: {minimum}")
    plt.ylabel("Malus points")
    
    plt.savefig("output_data/random_boxplot.png")